# Generated by Django 2.2.24 on 2022-05-10 14:13

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalApiCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('course_url', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('org', models.CharField(blank=True, default='', max_length=50)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
            ],
        ),
    ]
