# Generated by Django 2.2.24 on 2022-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalApiCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, default='', max_length=100)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('course_url', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('org', models.CharField(blank=True, default='', max_length=50)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
            ],
        ),
        migrations.DeleteModel(
            name='PortalApiCourses',
        ),
    ]
