# Generated by Django 2.2.24 on 2022-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0002_auto_20220510_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalapicourse',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
