# Generated by Django 2.2.24 on 2022-05-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0003_portalapicourse_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalApiOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('sort_number', models.PositiveSmallIntegerField(help_text='Posición de la organización a mostrar en el portal', unique=True)),
                ('url', models.CharField(blank=True, default='', help_text='Agregar URL solo si quiere mostrar los cursos de la organización de manera automática.', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='portalapicourse',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='portal_api.PortalApiOrg'),
        ),
    ]
