# Generated by Django 2.2.24 on 2022-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0004_auto_20220516_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalapicourse',
            name='self_paced',
            field=models.BooleanField(default=False, help_text='Enabled if is self-paced, Disabled if is instructor-paced'),
        ),
    ]
