# Generated by Django 2.2.24 on 2022-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0005_portalapicourse_self_paced'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalapicourse',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portalapicourse',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
